use_frameworks!

platform :ios, '9.0'

target 'CZBaseLib_Example' do
  pod 'CZBaseLib', :path => '../'

  target 'CZBaseLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
